### ISSUE TITLE
Image Grayscale

### ISSUE THREAD

**Issue by kalinchuk** [brunon80/expo-image-crop#3]
How easy would it be to add an option to make the image grayscale and/or have the ability to adjust the exposure/contrast?

**Comment by brunon80** [comment]
Hello! Thank you for your interest.
This module is based only on graphically exposing the capabilities of the ImageManipulator module of the Expo, adding grayscale would not be part of this scope, anyway, I tried to find a solution for your need and found this package npm : react-native-color-matrix-image-filters,
link: https://github.com/iyegoroff/react-native-color-matrix-image-filters#readme

But, you will need to do eject if you have not done it since it uses native modules.

I hope it helps!

**Comment by kalinchuk** [comment]
@brunon80 Thanks for looking into this. I was hoping to have an all-in-one solution to be able to take a picture of a document, crop and make it grayscale before upload.
